//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWIConnect.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWIConnect.Client.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received response {0} with content: &apos;{1}&apos;..
        /// </summary>
        public static string EndClientRequest {
            get {
                return ResourceManager.GetString("EndClientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; finished, time taken &apos;{1}&apos; milliseconds..
        /// </summary>
        public static string EndOfExecution {
            get {
                return ResourceManager.GetString("EndOfExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize configuration response &apos;{0}&apos;..
        /// </summary>
        public static string FailureDeserializingResponse {
            get {
                return ResourceManager.GetString("FailureDeserializingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to post file &apos;{0}&apos;..
        /// </summary>
        public static string FailurePostingFile {
            get {
                return ResourceManager.GetString("FailurePostingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; with last write access &apos;{1}&apos; sec ago, has not reached immutability interval of &apos;{2}&apos; sec - file is not being uploaded..
        /// </summary>
        public static string FileImmutabilityIntervalNotReached {
            get {
                return ResourceManager.GetString("FileImmutabilityIntervalNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; with size &apos;{1}&apos; mb exceeds size limit of &apos;{2}&apos; mb - file is not being uploaded..
        /// </summary>
        public static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; uploaded in &apos;{1}&apos; milliseconds..
        /// </summary>
        public static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process failed..
        /// </summary>
        public static string ProcessFailed {
            get {
                return ResourceManager.GetString("ProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started..
        /// </summary>
        public static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process finished, total execution time &apos;{0}&apos; milliseconds..
        /// </summary>
        public static string ProcessSucceeded {
            get {
                return ResourceManager.GetString("ProcessSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; with last write access &apos;{1}&apos;, has not reached send version after time stamp of &apos;{2}&apos; sec - file is not being uploaded..
        /// </summary>
        public static string SendVersionAfterTimeStampUtcNotReached {
            get {
                return ResourceManager.GetString("SendVersionAfterTimeStampUtcNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting request to &apos;{0}&apos; with content &apos;{1}&apos;..
        /// </summary>
        public static string StartClientRequest {
            get {
                return ResourceManager.GetString("StartClientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start getting file info &apos;{0}&apos;..
        /// </summary>
        public static string StartGettingIOFileInfo {
            get {
                return ResourceManager.GetString("StartGettingIOFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start getting file list from path &apos;{0}&apos; using search pattern &apos;{1}&apos;..
        /// </summary>
        public static string StartGettingIOFileList {
            get {
                return ResourceManager.GetString("StartGettingIOFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing file &apos;{0}&apos; on Thread &apos;{1}&apos;..
        /// </summary>
        public static string StartProcessFile {
            get {
                return ResourceManager.GetString("StartProcessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Directory &apos;{0}&apos;..
        /// </summary>
        public static string StartReadingIODirectory {
            get {
                return ResourceManager.GetString("StartReadingIODirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading content for file: &apos;{0}&apos;..
        /// </summary>
        public static string StartReadingIOFile {
            get {
                return ResourceManager.GetString("StartReadingIOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting FileInfo &apos;{0}&apos;..
        /// </summary>
        public static string StartReadingIOFileInfo {
            get {
                return ResourceManager.GetString("StartReadingIOFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading local configuration &apos;{0}&apos;..
        /// </summary>
        public static string StartReadingLocalConfiguration {
            get {
                return ResourceManager.GetString("StartReadingLocalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading remote configuration from &apos;{0}&apos;..
        /// </summary>
        public static string StartReadingRemoteConfiguration {
            get {
                return ResourceManager.GetString("StartReadingRemoteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start saving local configuration &apos;{0}&apos;..
        /// </summary>
        public static string StartSavingLocalConfiguration {
            get {
                return ResourceManager.GetString("StartSavingLocalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start upload file to url &apos;{0}&apos;, content &apos;{1}&apos;..
        /// </summary>
        public static string StartUploadFile {
            get {
                return ResourceManager.GetString("StartUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file &apos;{0}&apos;..
        /// </summary>
        public static string StartWritingIOFile {
            get {
                return ResourceManager.GetString("StartWritingIOFile", resourceCulture);
            }
        }
    }
}
